config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :new, :create, :show] do
    resources :doses, only: [:new, :create, :delete]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(doses_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Here are our Cocktails</h1>

<ul class="list-group"><% @cocktails.each do |cocktail| %>
 <li class="list-group-item"><%= link_to cocktail.name, cocktail_path(cocktail.id) %></li>
</ul><% end %>

<div>
  <%= link_to 'Create a cocktail', new_cocktail_path %>
</div>

app/views/cocktails/new.html.erb
<h1>Create a cocktail !</h1>

<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <!-- This div is centered and takes 6 columns -->
        <h1><%= @cocktail.name %></h1>
        <table class="table">
          <thead>
            <th>Description</th>
            <th>Ingredient</th>
            <th></th>
          </thead>
          <tbody>
            <% @cocktail.doses.each do |dose| %>
            <tr>
                <td><%= dose.description %></td>
                <td><%= dose.ingredient.name %></td>
                <td><%= link_to "Remove", dose_path(dose), method: :delete %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="d-flex justify-content-between">
            <%= link_to "Create a dose",  new_cocktail_dose_path(@cocktail.id) %>
            <%= link_to "Back to home", cocktails_path %>
        </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<h1>Create a dose !</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>